### ISSUE TITLE
Admin can add items in 'Done' state

### ISSUE THREAD

**Issue by Plunts** [StevenWeathers/wakita-retro-tool#24]
As an admin I can add items to the first three columns after the retro is set to "Done". I'm not sure if that's desired behaviour, but for me it seems a bit inconsistent.

**Comment by StevenWeathers** [comment]
I would agree its probably not ideal to let anyone alter the state of the first 3 columns after those steps has completed.

**Comment by StevenWeathers** [comment]
This will not be addressed as a completely new implementation has been developed on https://github.com/StevenWeathers/thunderdome-planning-poker
