### ISSUE TITLE
Suggestion: Limit number of votes

### ISSUE THREAD

**Issue by Plunts** [StevenWeathers/wakita-retro-tool#25]
To set a better focus in the meeting, we are limiting the number of votes each member has in each column. So e.g. one good thing and max. 4 bad things. It would be nice to configure and visualize this in the tool.

**Comment by StevenWeathers** [comment]
Great suggestion, I have not been actively enhancing this tool as I'm working on a reimagining of the tool within the more popular [Thunderdome](https://github.com/StevenWeathers/thunderdome-planning-poker) tool.

**Comment by Plunts** [comment]
Sounds like a great combination :) We are actually using both and were also about to ask if it would be possible to sync teams between the tools. Then maybe just take these suggestions for when you are integrating wakita into thunderdome.

**Comment by StevenWeathers** [comment]
This will not be implemented as https://github.com/StevenWeathers/thunderdome-planning-poker now has a retro feature, voting is per group not item there.
